Adds before and after step hooks
timjroberts/cucumber-js-tsflow pull request #145
Opened 2024-04-05 11:13 UTC by cjmarkham

Adds support for Cucumber `beforeStep` and `afterStep` hooks.

2024-04-05 16:25 UTC, Fryuni requested changes

2024-04-05 16:25 UTC, Fryuni commented on cucumber-tsflow-specs/features/hooks.feature
> +            }
This test does not validate the desired behavior that the hook runs before _each_ step. If it gets wired incorrectly internally to `Before,` this test won't detect it.

I think logging each function call would make the test clearer:
```suggestion
            class Steps {
                private counter = 0;

                @beforeStep()
                public hook() {
                    console.log(`${this.counter++} execution: beforeStep`);
                }

                @given("a step")
                public given() {
                    console.log(`${this.counter++} execution: given`);
                }

                @when("another step")
                public when() {
                    console.log(`${this.counter++} execution: when`);
                }
            }
```

Checking the logs for the entire scenario will show when each function is called, and the state is shared between them (called on the same instance).

2024-04-05 16:25 UTC, Fryuni commented on cucumber-tsflow-specs/features/hooks.feature
> +                }
Same for the `afterStep` hook

2024-04-05 16:27 UTC, Fryuni commented
Thanks for the PR!

The code looks great. I left two a small change requests to the tests to avoid future regressions.

2024-04-05 22:27 UTC, cjmarkham commented
> Thanks for the PR!
> 
> The code looks great. I left two small change requests to the tests to avoid future regressions.

I'll address when I can. Thanks for the review.

2024-04-06 23:01 UTC, cjmarkham commented
@Fryuni I've addressed your comments.

2024-04-06 23:46 UTC, Fryuni approved these changes

2024-04-06 23:51 UTC, Fryuni commented
Thank you for tackling this, I'll double-check it tomorrow (because I'm not sober right now) and if everything is ok, I'll merge and cut a release.

2024-04-07 19:11 UTC, merged